{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{default attribute_base=ContentClass}

<div class="block"></div>

{section show=$class_attribute.content.multioption_list}
    <table class="special" cellspacing="0">
    {section var=MultiOptionList loop=$class_attribute.content.multioption_list}
    <tr>
        <th class="tight"><input type="checkbox" name="{$attribute_base}_data_multioption_remove_{$class_attribute.id}[]" value="{$MultiOptionList.id}" title="{'Select multioption for removal.'|i18n( 'design/standard/content/datatype' )}" /></th>
        <th>{$MultiOptionList.index}</th>
        <th class="tight">{'Priority'|i18n( 'design/standard/content/datatype' )}:&nbsp;<input type="text" size="3" name = "{$attribute_base}_data_multioption_priority_{$class_attribute.id}_{$MultiOptionList.id}" value="{sum($MultiOptionList.index,1)}" /></th>
    </tr>

    <tr>
        <td colspan="3">

            <div class="block">
                <label for="ezcoa-{$class_attribute.id}_{$class_attribute.data_type_string}_{$MultiOptionList.id}_name">{'Name'|i18n( 'design/standard/content/datatype' )}:</label>
                <input id="ezcoa-{$class_attribute.id}_{$class_attribute.data_type_string}_{$MultiOptionList.id}" class="box ezcc-{$class_attribute.object.content_class.identifier} ezcca-{$class_attribute.object.content_class.identifier}_{$class_attribute.data_type_string}" type="text" name="{$attribute_base}_data_multioption_name_{$class_attribute.id}_{$MultiOptionList.id}" value="{$MultiOptionList.name}" />
                <input type="hidden" name="{$attribute_base}_data_multioption_id_{$class_attribute.id}[]" value="{$MultiOptionList.id}" />
            </div>

            <div class="block">
            <label>{'Options'|i18n( 'design/standard/content/datatype' )}:</label>
                {section show=$MultiOptionList.options}
                    <table class="list" cellspacing="0">
                    <tr>
                        <th class="tight">&nbsp;</th>
                        <th>{'Option'|i18n( 'design/standard/content/datatype' )}</th>
                    </tr>

                        {section var=OptionList loop=$MultiOptionList.options sequence=array( bglight, bgdark )}
                            <tr class="{$OptionList.sequence}">

                            {* Remove. *}
                            <td><input type="checkbox" name="{$attribute_base}_data_option_remove_{$class_attribute.id}_{$MultiOptionList.id}[]" value="{$OptionList.id}" title="{'Select option for removal.'|i18n('design/standard/content/datatype')}" /></td>

                            {* Option. *}
                            <td><input class="box" type="text" name="{$attribute_base}_data_option_value_{$class_attribute.id}_{$MultiOptionList.id}[]" value="{$OptionList.value}" /></td>

                            <input type="hidden" name="{$attribute_base}_data_option_id_{$class_attribute.id}_{$MultiOptionList.id}[]" value="{$OptionList.id}" />
                            <input type="hidden" name="{$attribute_base}_data_option_option_id_{$class_attribute.id}_{$MultiOptionList.id}[]" value="{$OptionList.option_id}" />
                            {*</td>*}
                            </tr>
                        {/section}
                            </table>
                {section-else}
                    <p>{'There are no options.'|i18n( 'design/standard/content/datatype' )}</p>
                {/section}

                {if $MultiOptionList.options}
                    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_remove-selected-option_{$MultiOptionList.id}]" value="{'Remove selected'|i18n('design/standard/content/datatype')}" title="{'Remove selected options.'|i18n( 'design/standard/content/datatype' )}" />
                {else}
                    <input class="button-disabled" type="submit" name="CustomActionButton[{$class_attribute.id}_remove-selected-option_{$MultiOptionList.id}]" value="{'Remove selected'|i18n('design/standard/content/datatype')}" disabled="disabled" />
                {/if}

                <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_new-option_{$MultiOptionList.id}]" value="{'Add option'|i18n('design/standard/content/datatype')}" title="{'Add a new option.'|i18n( 'design/standard/content/datatype' )}" />

                </div>
            </td>
        </tr>
    {/section}
    </table>
{section-else}
    <p>{'There are no multioptions.'|i18n( 'design/standard/content/datatype' )}</p>
{/section}


{if $class_attribute.content.multioption_list}
    <input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_remove_selected_multioption]" value="{'Remove selected'|i18n('design/standard/content/datatype')}" title="{'Remove selected multioptions.'|i18n( 'design/standard/content/datatype' )}" />
{else}
    <input class="button-disabled" type="submit" name="CustomActionButton[{$class_attribute.id}_remove_selected_multioption]" value="{'Remove selected'|i18n('design/standard/content/datatype')}" disabled="disabled" />
{/if}

<input class="button" type="submit" name="CustomActionButton[{$class_attribute.id}_new_multioption]" value="{'Add multioption'|i18n('design/standard/content/datatype')}" title="{'Add a new multioption.'|i18n('design/standard/content/datatype')}" />


{/default}