{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{default attribute_base=ContentObjectAttribute}

    {section show=$attribute.class_content.multioption_list}
        {section var=MultiOptionList loop=$attribute.class_content.multioption_list}

                    <div class="block" style="border-bottom: 1px solid #CCCCCC; font-weight: bold; height: 15px; vertical-align: middle; background-color: #F0F0F0; background-image: -moz-linear-gradient(center top , #FDFDFD, #E4E3E4); border: 1px solid #CCCCCC; color: #333333; padding: 5px; margin-bottom: 0;">
                        <span>{$MultiOptionList.name}</span>
                        <input type="hidden" name="{$attribute_base}_data_multioption_id_{$attribute.id}[]" value="{$MultiOptionList.id}" />
                    </div>

                    <div class="block" style="margin-top: 0; border-top: 0;">
                        {section show=$MultiOptionList.options}
                        <table class="list" cellspacing="0" style="border-top: 0;">
                            {section var=OptionList loop=$MultiOptionList.options sequence=array( bglight, bgdark )}
                            <tr class="{$OptionList.sequence}">
                                {* Option. *}
                                <td><input type="checkbox" {if nmo_in_array($OptionList.option_id, $attribute.content.multioption_list[$MultiOptionList.id].optionlist)} checked="checked"{/if}name="{$attribute_base}_data_option_id_{$attribute.id}_{$MultiOptionList.id}[]" value="{$OptionList.option_id}" />{$OptionList.value}</td>
                            </tr>
                            {/section}
                        </table>
                        {section-else}
                            <p>{'There are no options.'|i18n( 'design/standard/content/datatype' )}</p>
                        {/section}

                    </div>
        {/section}
    {section-else}
        <p>{'There are no multioptions.'|i18n( 'design/standard/content/datatype' )}</p>
    {/section}

{/default}

