{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block"></div>

{section var=Multioptions loop=$attribute.class_content.multioption_list}
<div class="block">
<label>{$Multioptions.item.name}:</label>
    <ul>
        {section var=Option loop=$Multioptions.options}            
            {if nmo_in_array($Option.item.option_id, $attribute.content.multioption_list[$Multioptions.item.id].optionlist)}
                <li><u><b>{$Option.item.value}</b></u></li>
            {else}
                <li>{$Option.item.value}</li>
            {/if}
        {/section}
    </ul>
</div>
{/section}